"""Add group_label and to DriveFile

Revision ID: 2d6f32d35c48
Revises: 80e79eef450b
Create Date: 2025-03-11 08:23:07.094373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6f32d35c48'
down_revision = '80e79eef450b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drive_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drive_files', schema=None) as batch_op:
        batch_op.drop_column('group_label')

    # ### end Alembic commands ###
