"""Add user_id to drive_folders

Revision ID: 3c6d2e294c13
Revises: cb0dc1f31a06
Create Date: 2025-03-07 13:32:03.776101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6d2e294c13'
down_revision = 'cb0dc1f31a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drive_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_drivefolders_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_drivefolders_user_id', 'user', ['fk_drivefolders_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drive_folders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_drivefolders_user_id')

    # ### end Alembic commands ###
