"""Nuevos datos del modelo User

Revision ID: 5b7ee486e7ef
Revises: 0c7f53ab727f
Create Date: 2025-02-24 11:58:27.801453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7ee486e7ef'
down_revision = '0c7f53ab727f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telephone')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
