"""Add login attempts and blocking fields to User

Revision ID: b43653ab94e6
Revises: 2d6f32d35c48
Create Date: 2025-04-01 10:20:07.220902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43653ab94e6'
down_revision = '2d6f32d35c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blocked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_column('blocked_until')
        batch_op.drop_column('login_attempts')

    # ### end Alembic commands ###
