"""Remove incorrect columns from UserRoles

Revision ID: ef6c51483de1
Revises: b43653ab94e6
Create Date: 2025-04-01 10:35:09.151423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6c51483de1'
down_revision = 'b43653ab94e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_column('login_attempts')
        batch_op.drop_column('blocked_until')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_until', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('login_attempts', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
